src/blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path

from rest_framework_jwt.views import obtain_jwt_token

from accounts.views import(login_view, register_view, logout_view)
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls', namespace='comments')),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include('posts.urls', namespace='posts')),
    
    path('api/token/auth/', obtain_jwt_token),
    path('api/posts/', include('posts.api.urls', namespace='posts-api')),
    path('api/comments/', include('comments.api.urls', namespace='comments-api')),
    path('api/users/', include('accounts.api.urls', namespace='users-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/api/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views
from .views import (
    PostCreateAPIView,
    PostDetailAPIView,
    PostListAPIView,
    PostDeleteAPIView,
    PostUpdateAPIView,
)

app_name = 'posts'

urlpatterns = [
    path('', PostListAPIView.as_view(), name='list'),
#     # path('category/', views.category_list, name='category_list'),
#     path('category/<slug>/', views.category_post, name='category_post'),
    path('create/', PostCreateAPIView.as_view(), name='create'),
    path('<slug>/', PostDetailAPIView.as_view(), name='detail'),
    path('<slug>/edit/', PostUpdateAPIView.as_view(), name='update'),
    path('<slug>/delete/', PostDeleteAPIView.as_view(), name='delete'),
 ]

src/posts/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
    category_post,
)

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
    # path('category/', views.category_list, name='category_list'),
    path('category/<slug>/', views.category_post, name='category_post'),
    path('create/', views.post_create, name='create'),
    path('<slug>/', views.post_detail, name='detail'),
    path('<slug>/edit/', views.post_update, name='update'),
    path('<slug>/delete/', views.post_delete),
]

src/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.safestring import mark_safe
from django.utils import timezone
from django.utils.text import slugify

from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


# Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" % (new_id, filename)

# category


class Category(models.Model):
    name = models.CharField(max_length=250, null=True)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("posts:category_post", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name

# end category


# Post


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             default=None, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=250, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    # models.TimeField(null=True, blank=True) #assume minutes
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post, Category


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False)) 
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "category",
            "image",
            "draft",
            "publish",
        ]

src/posts/api/views.py
# django rest api docs
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView, 
    UpdateAPIView,
    DestroyAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView,
)


from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)

from posts.models import Post

from .pagination import PostLimitOffsetPagination, PostPageNumberPagination
from .permissions import IsOwnerOrReadOnly
from .serializers import (
    PostCreateUpdateSerializer,
    PostDetailSerializer, 
    PostListSerializer
)


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    # permission_classes = [IsAuthenticated] # cz this permission is declared in project setting i rest framework

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [AllowAny]
    # lookup_url_kwarg = 'abc'


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]
    # lookup_url_kwarg = 'abc'

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)
        # email send_email


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]
    # lookup_url_kwarg = 'abc'

class PostListAPIView(ListAPIView):         #builtin search
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title','content','user__first_name']
    permission_classes = [AllowAny]
    pagination_class = PostLimitOffsetPagination  # PageNumberPagination

    def get_queryset(self, *args, **kwargs):        #q search
        # queryset_list = super(PostListAPIView, self).get_queryset(*args, **kwargs)
        queryset_list = Post.objects.all()  # filter(user=self.request.user)
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query) |
                Q(category__name__icontains=query)
            ).distinct()

        return queryset_list

src/posts/views.py
try:
    from urllib.parse import quote_plus  # python 3
except:
    pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q, Count
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post, Category

# category

# def category_list(request):
#     categories = Category.objects.all() # this will get all categories, you can do some filtering if you need (e.g. excluding categories without posts in it)

#     return render (request, 'category_list.html', {'categories': categories}) # blog/category_list.html should be the template that categories are listed.

# def category_detail(request, slug):
#     category = get_object_or_404(Category, slug=slug)

#     return render(request, 'category_detail.html', {'category': category}) # in this template, you will have access to category and posts under that category by (category.post_set).


def get_category_count():  # for making categories count which are present and then showing them
    query_set = Post.objects.values("category__name").annotate(
        Count("category__name")).order_by('category_id')
    return query_set


def category_post(request, slug):
    categories = Category.objects.get(slug=slug)
    post = Post.objects.filter(draft=False)

    if slug:
        category = get_object_or_404(Category, slug=slug)
        post = post.filter(category=category)

    context = {
        'categories': categories,
        'post': post,
        'category': category,
        "object_list": post,
    }

    return render(request, 'category_post.html', context)


# end category


def post_create(request):
    # if not request.user.is_staff or not request.user.is_superuser:
    # 	raise Http404
    if request.user.is_staff or request.user.is_superuser:
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            # message success
            messages.success(request, "Successfully Created")
            return HttpResponseRedirect(instance.get_absolute_url())
        context = {
            "form": form,
        }
        return render(request, "post_form.html", context)
    else:
        raise Http404


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated:
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
            parent=parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = instance.comments
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "comment_form": form,
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    category_count = get_category_count()
    # print(category_count)	# shows category count in terminal
    today = timezone.now().date()
    queryset_list = Post.objects.active()  # .order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query) |
            Q(category__name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 6)  # Show 6 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "List",
        "page_request_var": page_request_var,
        "today": today,
        "category_count": category_count,
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    # if not request.user.is_staff or not request.user.is_superuser:
    # 	raise Http404
    if request.user.is_staff or request.user.is_superuser:
        instance = get_object_or_404(Post, slug=slug)
        form = PostForm(request.POST or None,
                        request.FILES or None, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "Item Saved")
            return HttpResponseRedirect(instance.get_absolute_url())

        context = {
            "title": instance.title,
            "instance": instance,
            "form": form,
        }
        return render(request, "post_form.html", context)
    else:
        raise Http404


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted")
    return redirect("posts:list")

src/templates/base.html
{% load staticfiles %}

<!--DOCTYPE HTMLs-->
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block head_title %}BM Blogs{% endblock head_title %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
            integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

        <link rel="stylesheet" href='{% static "css/base.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
        <link rel="stylesheet" href='{% static "css/_variable.scss" %}'>
        <link rel="stylesheet" href='{% static "css/_bootswatch.scss" %}'>
        <style>
            {% block style %}

            {% endblock style %}
        </style>

        {% block head_extra %}{% endblock head_extra %}
    </head>

    <body>

        <div id="fb-root"></div>
        <script async defer src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2"></script>

        {% include "messages_display.html" %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'posts:list' %}"><img src="{% static 'img/navlogo1.png' %}"
                        height="35" width="35"> <i class="fas">Believe Master Blogs</i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "posts:list" %}"><i class="fas fa-home"> Home</i>
                                <!--go to post then list in posts.url-->
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        {% if request.user.is_staff or request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'posts:create' %}"><i class="far fa-plus-square">
                                    Create</i></a>
                            <!--go to create in posts.url if staff or superuser-->
                        </li>
                        {% block post_detail_link %}
                        <!--go to edit if staff or admin-->
                        {% endblock %}
                        {% endif %}
                        {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}"><i class="fas fa-user-plus">
                                    Register</i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"> Login</i></a>
                        </li>

                        {% else %}

                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                                <i class="fas fa-user"> Welcome {{ request.user }}</i>
                            </a>
                            <div class="dropdown-menu">
                                <a href="#" class="dropdown-item">
                                    <i class="fas fa-user-circle"> Profile</i>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <i class="fas fa-cog"> Settings</i>
                                </a>
                                <a href="{% url 'logout' %}" class="dropdown-item">
                                    <i class="fas fa-sign-out-alt"> Logout</i>
                                </a>
                            </div>
                        </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

            <div class="container pt-5">
                {% block content %}
                
                {% endblock content %}
            </div>

            <!-- Footer -->
            <footer class="py-5 mt-5 bg-dark">
                <div class="container">
                    <p class="m-0 float-left text-white">
                        Copyright &copy; Belive Master Blogs {% now "Y" as current_year %}{{ current_year }}
                    </p>
                </div>
                <div class="container">
                    <a class="m-0 float-right text-white" href="https://www.believemaster.github.io" title="Responsive framework">Design and coding by Yanik Kumar
                    </a>
                </div>
            </footer>

            <script src="https://code.jquery.com/jquery-3.3.1.js"
                integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>

            <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.1/marked.js"></script>

            <script type="text/javascript">
                $(document).ready(function () {
                    $(".content-markdown").each(function () {
                        var content = $(this).text()
                        var markedContent = marked(content)
                        $(this).html(markedContent)
                    })
                    $(".post-detail-item img").each(function () {
                        $(this).addClass("img-fluid");
                    })

                    var contentInput = $("#id_content");
                    function setContent(value) {
                        var markedContent = marked(value)
                        $("#preview-content").html(markedContent)
                        $("#preview-content img").each(function () {
                            $(this).addClass("img-fluid")
                        })
                    }
                    setContent(contentInput.val())
                    contentInput.keyup(function () {
                        var newContent = $(this).val()
                        setContent(newContent)
                    })
                    var titleInput = $("#id_title");

                    function setTitle(value) {
                        $("#preview-title").text(value)
                    }
                    setTitle(titleInput.val())
                    titleInput.keyup(function () {
                        var newContent = $(this).val()
                        setTitle(newContent)
                    })


                    $(".comment-reply-btn").click(function (e) {
                        e.preventDefault();
                        // $(this).parent().next(".comment-reply").fadeToggle();
                        // $(this).find(".comment-reply").fadeToggle();
                        // $(".comment-reply", this).fadeToggle();
                        $(".comment-reply").fadeToggle()
                    })
                    // preview-title
                    // preview-content
                })
            </script>
    </body>
</html>

src/templates/confirm_delete.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
<div class="container">
<div class="row h-100">
<div class="col-md-6 offset-md-3">
    <h1 class="display-4">Confirm Delete</h1>
        <form method="POST" action=".">{% csrf_token %}
            <p>Are you sure you want to delete : "{{ object.content }}" ?</p>
            <input type='submit' value='Confirm' class="btn btn-outline-danger">
            <a href="{{ object.get_absolute_url }}" class="btn btn-outline-secondary">Cancel</a>
        </form>
</div>
</div>
</div>

{% endblock content %}

src/templates/form.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %} 
{% block content %}

<div class="col-md-6 form-group">
  <h1 class="">{{ title }}</h1>
  <hr />
  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-secondary" value="{{ title }}" />
  </form>
  <br />
  <br />
</div>

{% endblock content %}

src/templates/post_detail.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block post_detail_link %}
<li class="nav-item">
    <a class="nav-link" href="{% url "posts:update" instance.slug %}"><i class="far fa-edit"> Edit</i></a>
</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8">
        <h1 class="mt-4">{{ title }} <small>{% if instance.draft %}<span
                    style='color:red;'>Draft</span>{% endif %}</small></h1>
        {% if instance.user.get_full_name %}
        <p class="lead">By: <b>{{ instance.user.get_full_name }}</b></p>
        {% endif %}
        <hr />
        <p>{{ instance.publish }}</p>
        </hr>
        <small>
            <p>Read Time : {% if instance.read_time <= 1 %} Less than a minute read {% else %}{{ instance.read_time }}
                Minutes read{% endif %}</p>
        </small>
        <hr />
        {% if instance.image %}
        <div class="text-center">
            <img class="rounded mx-auto img-fluid" src="{{ instance.image.url }}" width="480" height="360">
        </div>
        {% endif %}


        {% comment %} <p>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                Facebook
            </a>
            <a
                href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
                Twitter
            </a>
            <a
                href='https://plus.google.com/share?url={{ request.build_absolute_uri }}&title={{ share_string }}'>Google+</a>
            <a
                href="https://www.linkedin.com/shareArticle?mini=true&summary={{ share_string }}&url={{ request.build_absolute_uri }}">
                Linkedin
            </a>
        </p> {% endcomment %}

        <div class="row">
            <div class="col-sm-12">

                <div class="post-detail-item"> {{ instance.get_markdown }} </div>

                <hr>
            </div>
        </div>
        <p>
            <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count"
                data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
        </p>

        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            {% if request.user.is_authenticated %}
            <div class="card-body">
                <form class="form-group" method="POST" action=".">
                    {{ comment_form|crispy }} {% csrf_token %}
                    <input type='submit' value='Post Comment' class="btn btn-outline-dark">
                </form>
            </div>
            {% else %}
            <p class="lead">You must Login to Comment</p>
            {% endif %}
            {% for comment in comments %}

            <blockquote class="blockquote media mb-4 ml-4">
                <div class="media-body">
                    <p class="mb-0">{{ comment.content }}</p>
                    <small>
                        <footer class="blockquote-footer">via {{ comment.user }} | {{ comment.timestamp|timesince }} ago
                            |
                            {% if comment.children.count > 0  %}{{ comment.children.count }}
                            Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %}<a
                                class="comment-reply-btn" href="#">Reply</a> | <a class=""
                                href="{{ comment.get_absolute_url }}">Thread</a></footer>
                    </small>
                </div>
                <div class="comment-reply">
                    {% for child_comment in comment.children %}
                    <blockquote class="blockquote media mb-4 ml-4">
                        <div class="media-body">
                            <p class="mb-0">{{ child_comment.content }}</p>
                        </div>
                        <small>
                            <footer class="blockquote-footer">via {{ child_comment.user }} |
                                {{ child_comment.timestamp|timesince }} ago</footer>
                        </small>
                    </blockquote>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                    <form class="form-group" method="POST" action=".">{% csrf_token %}
                        {{ comment_form|crispy }}
                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        <input type='submit' value='Reply' class="btn btn-outline-dark">
                    </form>
                    {% else %}
                    <p>You must Login to Comment</p>
                    {% endif %}
                </div>
            </blockquote>
            </hr>
            {% endfor %}
        </div>
    </div>
    <!-- Can Add Sidebar here but skip for advertisements -->

</div>
{% endblock content %}